version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.17.5
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: cimg/node:14.17.5
    steps:
      - checkout
      - run: echo "testing code"
      - run: npm install
      - run: npm test
workflows:
  build_test:
    jobs:
      - build
      - test